# Generated by Django 5.0.6 on 2024-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='location',
        ),
        migrations.AddField(
            model_name='photo',
            name='latitude',
            field=models.FloatField(default=4.6628864),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='longitude',
            field=models.FloatField(default=-74.0786176),
            preserve_default=False,
        ),
    ]
